export const DEFAULT_STYLE_PROPERTIES = [
  "display",
  "position",
  "top",
  "right",
  "bottom",
  "left",
  "z-index",
  "box-sizing",
  "width",
  "height",
  "min-width",
  "max-width",
  "min-height",
  "max-height",
  "margin-top",
  "margin-right",
  "margin-bottom",
  "margin-left",
  "padding-top",
  "padding-right",
  "padding-bottom",
  "padding-left",
  "font-family",
  "font-size",
  "font-weight",
  "font-style",
  "line-height",
  "letter-spacing",
  "text-align",
  "text-transform",
  "color",
  "background-color",
  "background-image",
  "background-size",
  "background-position",
  "border-top-width",
  "border-right-width",
  "border-bottom-width",
  "border-left-width",
  "border-top-color",
  "border-right-color",
  "border-bottom-color",
  "border-left-color",
  "border-radius",
  "box-shadow",
  "opacity",
  "overflow",
  "gap",
  "row-gap",
  "column-gap",
  "justify-content",
  "align-items",
  "flex-direction",
  "grid-template-columns"
];

export const DEFAULT_SELECTORS = [
  "body",
  "header",
  "nav",
  "main",
  "footer",
  "section",
  "article",
  "h1",
  "h2",
  "h3",
  "p",
  "a",
  "button",
  "img",
  "form",
  "[class*='hero' i]",
  "[class*='card' i]",
  "[class*='button' i]",
  "[class*='cta' i]"
];
